Web Scraping NFL data project goal is to create a .csv file of relevant NFL stats for the 2021 Season

In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
from pandas import DataFrame
import numpy as np

In [2]:
year = 2021
url = "https://www.pro-football-reference.com/years/{}/fantasy.htm".format(year)
html = urlopen(url)
soup = BeautifulSoup(html)
categories = [th.getText() for th in soup.findAll('tr')[1].findAll('th',class_= "poptip")]
categories = categories[1:26]

In [3]:
table_body = soup.findAll('tr', class_ = lambda table_rows: table_rows != "thead")
table_data = [[td.getText() for td in table_body[i].findAll('td')]
                for i in range(len(table_body))]
for data in table_data:
    del data[-7:]
table_data = table_data[2:]

In [4]:
stats = pd.DataFrame(data = table_data, columns = categories)
stats.head()

,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,...,Tgt,Rec,Yds,Y/R,TD,Fmb,FL,TD,2PM,2PP
0,Chris Johnson*+,TEN,RB,24,16,16,0,1,0,0,...,71,50,503,10.06,2,3,3,16,1,
1,Adrian Peterson*+,MIN,RB,24,16,15,0,0,0,0,...,57,43,436,10.14,0,7,6,18,,
2,Maurice Jones-Drew*,JAX,RB,24,16,16,0,0,0,0,...,71,53,374,7.06,1,2,1,16,,
3,Aaron Rodgers*,GNB,QB,26,16,16,350,541,4434,30,...,0,0,0,,0,10,4,5,,3
4,Andre Johnson*+,HOU,WR,28,16,16,0,0,0,0,...,171,101,1569,15.53,9,1,,9,1,

In [5]:
stats = stats.replace(r'', 0, regex=True)
stats.head()

,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,...,Tgt,Rec,Yds,Y/R,TD,Fmb,FL,TD,2PM,2PP
0,Chris Johnson*+,TEN,RB,24,16,16,0,1,0,0,...,71,50,503,10.06,2,3,3,16,1,0
1,Adrian Peterson*+,MIN,RB,24,16,15,0,0,0,0,...,57,43,436,10.14,0,7,6,18,0,0
2,Maurice Jones-Drew*,JAX,RB,24,16,16,0,0,0,0,...,71,53,374,7.06,1,2,1,16,0,0
3,Aaron Rodgers*,GNB,QB,26,16,16,350,541,4434,30,...,0,0,0,0,0,10,4,5,0,3
4,Andre Johnson*+,HOU,WR,28,16,16,0,0,0,0,...,171,101,1569,15.53,9,1,0,9,1,0

In [6]:
stats.to_csv('{}playerstats.csv'.format(year))